MODEL:
  TYPE: swin
  NAME: swin_base_patch4_window12_384
  DROP_PATH_RATE: 0.5
  PRETRAIN_CKPT: "./pretrained_ckpt/swin_base_patch4_window12_384_22k.pth"
  SWIN:
    FINAL_UPSAMPLE: "expand_first"
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    DECODER_DEPTHS: [ 2, 2, 2, 1]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 12